export const initialItems = new Array(100000).fill(0).map((_, i) => {
  return {
    id: i,
    isSelected: i === 9999,
  };
});

export const shuffle = (array) => {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]]; // Swap elements
  }
  return array;
};

export const fruits = [
  "Pineapple",
  "Apple",
  "Banana",
  "Orange",
  "Mango",
  "Grapes",
  "Watermelon",
  "Strawberry",
  "Blueberry",
  "Raspberry",
  "Blackberry",
  "Cherry",
  "Peach",
  "Plum",
  "Apricot",
  "Kiwi",
  "Papaya",
  "Pomegranate",
  "Lychee",
  "Dragonfruit",
  "Avocado",
  "Guava",
  "Passionfruit",
  "Durian",
  "Jackfruit",
  "Cantaloupe",
  "Honeydew",
  "Fig",
  "Tangerine",
  "Clementine",
  "Mandarin",
  "Lemon",
  "Lime",
  "Coconut",
  "Pear",
  "Persimmon",
  "Mulberry",
  "Gooseberry",
  "Cranberry",
  "Boysenberry",
  "Elderberry",
  "Date",
  "Raisin",
  "Sultana",
  "Starfruit",
  "Rambutan",
  "Longan",
  "Nectarine",
  "Quince",
  "Tamarind",
  "Soursop",
  "Salak",
  "Chico",
  "Custard Apple",
  "Acerola",
  "Bilberry",
  "Jabuticaba",
  "Jujube",
  "Langsat",
  "Mangosteen",
  "Marionberry",
  "Miracle Fruit",
  "Olive",
  "Prickly Pear",
  "Sapodilla",
  "Santol",
  "Sugar Apple",
  "Ugli Fruit",
  "Yuzu",
  "Zucchini (technically a fruit)",
  "Ackee",
  "Amla",
  "Buddha's Hand",
  "Calamansi",
  "Cherimoya",
  "Hawthorn",
  "Kaffir Lime",
  "Kumquat",
  "Lucuma",
  "Medlar",
  "Nance",
  "Pepino",
  "Pitanga",
  "Pummelo",
  "Rowan",
  "Sea Buckthorn",
  "Sloe",
  "Surinam Cherry",
  "White Currant",
  "Yellow Passionfruit",
  "Carambola",
  "Jostaberry",
  "Wineberry",
  "Feijoa",
  "Huckleberry",
  "Loquat",
  "Pomelo",
];
